use crate::error::CliError;
use crate::theme;
use std::path::Path;

use super::config::AdkConfig;

pub fn generate(config: &AdkConfig, project_dir: &Path) -> Result<String, CliError> {
    let exposed: Vec<String> = config
        .ports
        .exposed_ports()
        .iter()
        .map(|p| format!("EXPOSE {}", p))
        .collect();

    let expose_lines = if exposed.is_empty() {
        "EXPOSE 8080".to_string()
    } else {
        exposed.join("\n")
    };

    let has_requirements = project_dir.join("requirements.txt").exists();
    let pip_install = if has_requirements {
        "COPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt"
    } else {
        "# No requirements.txt found - add one if your tools need Python packages"
    };

    let has_tools = project_dir.join("tools").is_dir();
    let copy_tools = if has_tools {
        "COPY tools/ tools/"
    } else {
        "# No tools/ directory"
    };

    let has_skills = project_dir.join("skills").is_dir();
    let copy_skills = if has_skills {
        "COPY skills/ skills/"
    } else {
        "# No skills/ directory"
    };

    let has_knowledge = project_dir.join("knowledge").is_dir();
    let copy_knowledge = if has_knowledge {
        "COPY knowledge/ knowledge/"
    } else {
        "# No knowledge/ directory"
    };

    let has_env = project_dir.join(".env").exists();
    let copy_env = if has_env {
        "COPY .env .env"
    } else {
        "# No .env file - pass env vars via docker run -e or --env-file"
    };

    let dockerfile = format!(
        r#"# Auto-generated by forge adk build
# Project: {name}

FROM python:3.12-slim

# Install forge CLI
COPY --from=forge-binary /usr/local/bin/forge /usr/local/bin/forge

WORKDIR /app

# Python dependencies
{pip_install}

# Project files
COPY adk.yaml .
COPY agents/ agents/
{copy_tools}
{copy_knowledge}
{copy_skills}
{copy_env}

# Exposed ports
{expose_lines}

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s \
  CMD curl -f http://localhost:{health_port}/health || exit 1

ENTRYPOINT ["forge", "serve", "all", "--config-from-adk", "/app/adk.yaml"]
"#,
        name = config.name,
        pip_install = pip_install,
        copy_tools = copy_tools,
        copy_knowledge = copy_knowledge,
        copy_skills = copy_skills,
        copy_env = copy_env,
        expose_lines = expose_lines,
        health_port = config.ports.user.port,
    );

    Ok(dockerfile)
}

pub fn write_dockerfile(config: &AdkConfig, project_dir: &Path) -> Result<(), CliError> {
    let content = generate(config, project_dir)?;
    let path = project_dir.join("Dockerfile");
    std::fs::write(&path, &content).map_err(CliError::Io)?;
    println!(
        "  {} Generated {}",
        theme::success("✓"),
        theme::value("Dockerfile")
    );
    Ok(())
}
