/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum AgentState {
  Idle = 'Idle',
  Thinking = 'Thinking',
  ExecutingTool = 'ExecutingTool',
  WaitingForHuman = 'WaitingForHuman',
  Completed = 'Completed',
  Error = 'Error',
  Stopped = 'Stopped'
}
export interface JsStepType {
  kind: string
  toolName?: string
  callId?: string
}
export interface JsStepResult {
  kind: string
  response?: string
  toolCalls?: Array<JsToolCall>
  prompt?: string
  error?: string
}
export interface JsAgentStep {
  stepNumber: number
  stepType: JsStepType
  result: JsStepResult
  durationMs: number
}
export const enum AutomationTaskStatus {
  Pending = 'Pending',
  Running = 'Running',
  Completed = 'Completed',
  Failed = 'Failed',
  Cancelled = 'Cancelled'
}
export const enum AutomationScheduleConfig {
  Once = 'Once',
  Interval = 'Interval',
  Cron = 'Cron'
}
export interface JsAutomationConfig {
  id: string
  name: string
  description: string
  enabled: boolean
  maxRetries: number
  timeoutSecs: number
}
export interface JsTaskContext {
  input?: any
  state: any
}
export interface JsTaskOutput {
  success: boolean
  message: string
  data?: any
  durationMs: number
}
export interface JsExecutionRecord {
  executionId: string
  taskId: string
  status: string
  startedAt: number
  endedAt?: number
}
export interface JsChunk {
  text: string
  index: number
  startChar: number
  endChar: number
}
export declare function chunk(text: string, chunkSize: number, overlap: number, strategy: string): Array<JsChunk>
export const enum SummarizationStrategy {
  KeepRecent = 'KeepRecent',
  Summarize = 'Summarize',
  ChunkedSummary = 'ChunkedSummary',
  PreserveSystem = 'PreserveSystem'
}
export const enum TipErrorKind {
  Authentication = 'Authentication',
  RateLimit = 'RateLimit',
  InvalidRequest = 'InvalidRequest',
  Server = 'Server',
  Network = 'Network',
  Timeout = 'Timeout',
  Stream = 'Stream',
  ModelNotFound = 'ModelNotFound',
  Json = 'Json',
  Config = 'Config',
  Internal = 'Internal',
  Other = 'Other'
}
export interface JsTestCase {
  input: string
  expected: string
  name?: string
  tags: Array<string>
  weight: number
}
export interface JsEvalResult {
  passed: boolean
  score: number
  reason?: string
}
export interface JsCaseResult {
  input: string
  expected: string
  actual: string
  eval: JsEvalResult
  durationMs: number
}
export interface JsSuiteStats {
  total: number
  passed: number
  failed: number
  passRate: number
  avgScore: number
  weightedAvgScore: number
  durationMs: number
}
export interface JsSuiteResult {
  name: string
  evaluator: string
  results: Array<JsCaseResult>
  stats: JsSuiteStats
}
export interface JsEvent {
  id: string
  eventType: string
  data: any
  source?: string
  correlationId?: string
}
export interface GuardrailResult {
  passed: boolean
  value: string
  message: string
  guardrailName: string
}
export interface PiiMatch {
  piiType: string
  value: string
}
export declare function detectPii(text: string): GuardrailResult
export declare function redactPii(text: string): string
export declare function findPii(text: string): Array<PiiMatch>
export declare function detectInjection(text: string): GuardrailResult
export declare function checkAll(text: string): GuardrailResult
export const enum RiskLevel {
  Low = 'Low',
  Medium = 'Medium',
  High = 'High',
  Critical = 'Critical'
}
export const enum ApprovalStatus {
  Pending = 'Pending',
  Approved = 'Approved',
  Denied = 'Denied',
  Timeout = 'Timeout'
}
export interface JsApprovalRequest {
  id: string
  action: string
  description: string
  riskLevel: string
  toolName?: string
  arguments?: any
}
export interface JsApprovalResult {
  approved: boolean
  reason?: string
  modifiedArgs?: any
}
export declare function createApprovalRequest(action: string, description: string, riskLevel: RiskLevel, toolName?: string | undefined | null, arguments?: any | undefined | null): JsApprovalRequest
export interface JsHookContext {
  event: string
  data: any
  correlationId?: string
}
export const enum JsHookResult {
  Continue = 'Continue',
  Skip = 'Skip',
  Abort = 'Abort'
}
export const enum ImageSize {
  Size256x256 = 'Size256x256',
  Size512x512 = 'Size512x512',
  Size1024x1024 = 'Size1024x1024',
  Size1792x1024 = 'Size1792x1024',
  Size1024x1792 = 'Size1024x1792'
}
export const enum ImageQuality {
  Standard = 'Standard',
  Hd = 'Hd'
}
export const enum ImageStyle {
  Natural = 'Natural',
  Vivid = 'Vivid'
}
export const enum ImageResponseFormat {
  Url = 'Url',
  B64Json = 'B64Json'
}
export interface JsImageData {
  url?: string
  b64Json?: string
  revisedPrompt?: string
}
export interface JsImageResponse {
  created: number
  data: Array<JsImageData>
}
export declare function generateImage(client: AsyncForgeClient, request: ImageRequest): Promise<JsImageResponse>
export interface JsDocument {
  id: string
  content: string
  namespace?: string
  source?: string
  metadata: Record<string, any>
}
export interface JsSearchResult {
  document: JsDocument
  score: number
  highlights: Array<string>
}
export interface JsKnowledgeStats {
  documentCount: number
  namespaceCount: number
  namespaces: Array<string>
}
export const enum TransportType {
  Stdio = 'Stdio',
  Sse = 'Sse',
  Http = 'Http'
}
export const enum SpanKind {
  Internal = 'Internal',
  Server = 'Server',
  Client = 'Client',
  Producer = 'Producer',
  Consumer = 'Consumer'
}
export const enum SpanStatus {
  Unset = 'Unset',
  Ok = 'Ok',
  Error = 'Error'
}
export interface JsSpanContext {
  traceId: string
  spanId: string
  parentSpanId?: string
}
export interface JsIntent {
  name: string
  confidence: number
  entities: Record<string, string>
  input: string
}
export interface JsRoutingDecision {
  agent: string
  intent: JsIntent
  confidence: number
}
export interface JsSessionMessage {
  role: string
  content: string
  agent?: string
  timestamp: number
}
export interface JsSession {
  id: string
  history: Array<JsSessionMessage>
  createdAt: number
  updatedAt: number
  metadata: Record<string, any>
}
export interface JsWorkflowStep {
  id: string
  name: string
  agent: string
  input: any
  dependsOn: Array<string>
  condition?: string
  timeoutSecs?: number
  retries?: number
}
export interface JsWorkflow {
  id: string
  name: string
  steps: Array<JsWorkflowStep>
}
export const enum OrchestrationStepStatus {
  Pending = 'Pending',
  Running = 'Running',
  Completed = 'Completed',
  Failed = 'Failed',
  Skipped = 'Skipped'
}
export interface JsOrchestrationResult {
  agent: string
  response: string
  sessionId: string
}
/**
 * Initialise the global OTel tracer provider + W3C propagator.
 *
 * All fields are optional; omitted values fall back to the matching
 * `OTEL_*` env var. Idempotent, safe to call multiple times. When
 * the native module was built without the `otel` cargo feature, this
 * is a no-op that succeeds silently.
 *
 * JS usage:
 * ```javascript
 * const forge = require('@liteforge/sdk');
 * forge.initOtel({
 *   endpoint: 'https://irn08782.apps.dynatrace.com/api/v2/otlp/v1/traces',
 *   headers: { Authorization: 'Api-Token <token>' },
 *   serviceName: 'btsales-agent',
 * });
 * ```
 */
export interface InitOtelOptions {
  endpoint?: string
  headers?: Record<string, string>
  serviceName?: string
  resourceAttributes?: Record<string, string>
  capturePrompts?: boolean
}
export declare function initOtel(options?: InitOtelOptions | undefined | null): void
/**
 * True when the native module was built with `--features otel`.
 * When false, [`init_otel`] is a no-op.
 */
export declare function otelFeatureEnabled(): boolean
export interface PipelineStepOutput {
  text: string
  data: any
  continuePipeline: boolean
}
export declare function createStepOutput(text: string): PipelineStepOutput
export declare function createStepOutputWithData(text: string, data: any): PipelineStepOutput
export declare function createStopOutput(text: string): PipelineStepOutput
export interface JsEmbeddedDocument {
  id: string
  content: string
  embedding: Array<number>
  metadata: Record<string, string>
}
export interface JsVectorSearchResult {
  document: JsEmbeddedDocument
  score: number
}
export declare function cosineSimilarity(a: Array<number>, b: Array<number>): number
export declare function dotProduct(a: Array<number>, b: Array<number>): number
export declare function euclideanDistance(a: Array<number>, b: Array<number>): number
export declare function normalize(v: Array<number>): Array<number>
export const enum ScheduleType {
  Once = 'Once',
  Interval = 'Interval',
  Cron = 'Cron'
}
export const enum JobStatus {
  Pending = 'Pending',
  Running = 'Running',
  Completed = 'Completed',
  Failed = 'Failed',
  Cancelled = 'Cancelled'
}
export interface JsSkillConfig {
  name: string
  description: string
  systemPrompt?: string
  model?: string
  temperature?: number
  maxTokens?: number
}
export interface JsSkillInput {
  text: string
  parameters: Record<string, string>
}
export interface JsSkillOutput {
  text: string
  metadata: Record<string, any>
}
export declare function getSummarizeSkill(): JsSkillConfig
export declare function getTranslateSkill(): JsSkillConfig
export declare function getExtractSkill(): JsSkillConfig
export declare function getRewriteSkill(): JsSkillConfig
export declare function getQaSkill(): JsSkillConfig
export interface JsToolResultData {
  toolCallId?: string
  name: string
  success: boolean
  result?: string
  error?: string
  executionTimeMs?: number
}
export interface SchemaValidationError {
  path: string
  message: string
}
export declare function validateJsonSchema(value: any, schema: any): Array<SchemaValidationError>
export interface Message {
  role: string
  content?: string
  name?: string
  toolCalls?: Array<JsToolCall>
  toolCallId?: string
}
export interface JsToolCall {
  index?: number
  id: string
  callType: string
  function: JsFunctionCall
}
export interface JsFunctionCall {
  name: string
  arguments: string
}
export interface Usage {
  promptTokens: number
  completionTokens: number
  totalTokens: number
}
export interface Choice {
  index: number
  message: Message
  finishReason?: string
}
export interface ChatCompletion {
  id: string
  object: string
  created: number
  model: string
  choices: Array<Choice>
  usage?: Usage
}
export interface ChoiceDelta {
  role?: string
  content?: string
  toolCalls?: Array<JsToolCall>
}
export interface StreamChoice {
  index: number
  delta: ChoiceDelta
  finishReason?: string
}
export interface ChatCompletionChunk {
  id: string
  object: string
  created: number
  model: string
  choices: Array<StreamChoice>
}
export interface JsModel {
  id: string
  object: string
  created?: number
  ownedBy?: string
}
export interface JsModelList {
  object: string
  data: Array<JsModel>
}
export interface JsEmbeddingData {
  object: string
  embedding: Array<number>
  index: number
}
export interface JsEmbeddingUsage {
  promptTokens: number
  totalTokens: number
}
export interface JsEmbeddingResponse {
  object: string
  data: Array<JsEmbeddingData>
  model: string
  usage: JsEmbeddingUsage
}
export interface JsToolDefinition {
  toolType: string
  function: JsFunctionDefinition
}
export interface JsFunctionDefinition {
  name: string
  description?: string
  parameters?: any
}
export declare function createMessageUser(content: string): Message
export declare function createMessageSystem(content: string): Message
export declare function createMessageAssistant(content: string): Message
export declare function createMessageTool(toolCallId: string, content: string): Message
export declare class JsAgentMemory {
  constructor()
  addMessage(role: string, content: string): void
  messages(): Array<Message>
  clearShortTerm(): void
  remember(key: string, value: any): void
  recall(key: string): any | null
  forget(key: string): boolean
  setWorking(key: string, value: any): void
  getWorking(key: string): any | null
  clearWorking(): void
  messageCount(): number
}
export declare class JsAgentConfig {
  constructor(name: string)
  withSystemPrompt(prompt: string): this
  withModel(model: string): this
  withMaxSteps(maxSteps: number): this
  withTemperature(temperature: number): this
  withMaxTokens(maxTokens: number): this
  withStreaming(streaming: boolean): this
  withTool(toolName: string): this
  get name(): string
  get systemPrompt(): string | null
  get model(): string | null
  get maxSteps(): number
}
export declare class ToolCallingAgent {
  constructor(client: AsyncForgeClient)
  run(input: string): Promise<string>
  name(): Promise<string>
  history(): Promise<Array<JsAgentStep>>
  clearHistory(): Promise<void>
}
export declare class AutomationBuilder {
  constructor(id: string)
  name(name: string): this
  description(desc: string): this
  everySeconds(seconds: number): this
  everyMinutes(minutes: number): this
  everyHours(hours: number): this
  cron(expression: string): this
  retries(maxRetries: number): this
  timeout(timeoutSecs: number): this
  build(): JsAutomationConfig
}
export declare class ForgeClientBuilder {
  constructor()
  apiKey(key: string): this
  defaultModel(model: string): this
  baseUrl(url: string): this
  timeoutSecs(secs: number): this
  /** Static headers attached to every outbound request. */
  defaultHeaders(headers: Record<string, string>): this
  /** Sticky metadata merged into every request body's top-level `metadata`. */
  defaultMetadata(metadata: Record<string, any>): this
  /** OTel exporter endpoint (e.g. Dynatrace tenant URL). */
  otelEndpoint(endpoint: string): this
  /** OTel exporter headers (e.g. {"Authorization": "Api-Token …"}). */
  otelHeaders(headers: Record<string, string>): this
  /** `service.name` resource attribute. */
  otelServiceName(name: string): this
  /** Additional OTel resource attributes (e.g. `deployment.environment`). */
  otelResourceAttributes(attrs: Record<string, string>): this
  /**
   * Capture prompt/completion content on LLM spans (off by default;
   * non-prod debug only).
   */
  otelCapturePrompts(enabled: boolean): this
  build(): AsyncForgeClient
}
export declare class AsyncForgeClient {
  constructor()
  static withConfig(apiKey?: string | undefined | null, defaultModel?: string | undefined | null, baseUrl?: string | undefined | null, timeoutSecs?: number | undefined | null): AsyncForgeClient
  static builder(): AsyncForgeClient
  get model(): string
  get baseUrl(): string
  complete(messages: Array<Message>): Promise<ChatCompletion>
  completeWithModel(model: string, messages: Array<Message>): Promise<ChatCompletion>
  chatCompletions(model: string, messages: Array<Message>, temperature?: number | undefined | null, maxTokens?: number | undefined | null, tools?: Array<JsToolDefinition> | undefined | null, topP?: number | undefined | null, stop?: Array<string> | undefined | null, presencePenalty?: number | undefined | null, frequencyPenalty?: number | undefined | null, user?: string | undefined | null, metadata?: Record<string, any> | undefined | null): Promise<ChatCompletion>
  completeStream(messages: Array<Message>): Promise<CompletionStream>
  listModels(): Promise<JsModelList>
  embed(text: string): Promise<JsEmbeddingResponse>
  embedBatch(texts: Array<string>): Promise<JsEmbeddingResponse>
}
export declare class ConversationConfig {
  constructor(maxTokens?: number | undefined | null, targetTokens?: number | undefined | null, preserveRecent?: number | undefined | null, strategy?: SummarizationStrategy | undefined | null)
}
export declare class ManagedConversation {
  constructor()
  setSystem(content: string): void
  addUserMessage(content: string): void
  addAssistantMessage(content: string): void
  messages(): Array<Message>
  len(): number
  isEmpty(): boolean
  estimatedTokens(): number
  clear(): void
}
export declare class CompactingConversation {
  constructor(config: ConversationConfig)
  setSystem(content: string): void
  addUserMessage(content: string): void
  addAssistantMessage(content: string): void
  messages(): Array<Message>
  needsCompaction(): boolean
  compact(): any
  estimatedTokens(): number
}
export declare class EvalSuite {
  constructor(name: string)
  addCase(input: string, expected: string): void
  addNamedCase(input: string, expected: string, name: string): void
  runExactMatch(outputs: Array<string>): JsSuiteResult
  runContains(outputs: Array<string>): JsSuiteResult
  runRegex(outputs: Array<string>): JsSuiteResult
  runSimilarity(outputs: Array<string>, threshold: number): JsSuiteResult
  runJsonMatch(outputs: Array<string>): JsSuiteResult
  len(): number
  isEmpty(): boolean
}
export declare class EventType {
  static agentStart(): EventType
  static agentEnd(): EventType
  static agentStep(): EventType
  static agentError(): EventType
  static toolCall(): EventType
  static toolResult(): EventType
  static toolError(): EventType
  static llmRequest(): EventType
  static llmResponse(): EventType
  static llmStream(): EventType
  static llmError(): EventType
  static knowledgeSearch(): EventType
  static knowledgeUpload(): EventType
  static knowledgeDelete(): EventType
  static custom(): EventType
  isAgentEvent(): boolean
  isToolEvent(): boolean
  isLlmEvent(): boolean
  asString(): string
}
export declare class EventBus {
  constructor()
  static withCapacity(capacity: number): EventBus
  publish(eventType: EventType, data?: any | undefined | null): string
  subscriberCount(): number
}
export declare class HookEvent {
  static beforeAgentStart(): HookEvent
  static afterAgentEnd(): HookEvent
  static beforeAgentStep(): HookEvent
  static afterAgentStep(): HookEvent
  static beforeToolCall(): HookEvent
  static afterToolCall(): HookEvent
  static beforeLlmRequest(): HookEvent
  static afterLlmResponse(): HookEvent
  static beforeKnowledgeSearch(): HookEvent
  static afterKnowledgeSearch(): HookEvent
  asString(): string
}
export declare class HookManager {
  constructor()
  registerContinue(name: string, priority?: number | undefined | null): void
  registerSkip(name: string, priority?: number | undefined | null): void
  registerAbort(name: string, message: string, priority?: number | undefined | null): void
  unregister(name: string): boolean
  run(event: HookEvent, data?: any | undefined | null): string
  len(): number
  isEmpty(): boolean
  hookNames(): Array<string>
  clear(): void
}
export declare class ImageRequest {
  constructor(prompt: string)
  model(model: string): this
  n(n: number): this
  size(size: ImageSize): this
  quality(quality: ImageQuality): this
  style(style: ImageStyle): this
  responseFormat(format: ImageResponseFormat): this
}
export declare class SearchOptions {
  constructor()
  limit(limit: number): this
  namespace(namespace: string): this
  filter(key: string, value: string): this
  includeHighlights(include: boolean): this
}
export declare class ListOptions {
  constructor()
  limit(limit: number): this
  offset(offset: number): this
  namespace(namespace: string): this
}
export declare class LocalKnowledgeBackend {
  constructor()
  search(query: string, options?: SearchOptions | undefined | null): Array<JsSearchResult>
  upload(documents: Array<JsDocument>): number
  get(id: string): JsDocument | null
  delete(id: string): boolean
  update(document: JsDocument): boolean
  list(options?: ListOptions | undefined | null): Array<JsDocument>
  stats(): JsKnowledgeStats
  clear(namespace?: string | undefined | null): number
}
export declare class McpServerConfig {
  static stdio(name: string, command: string): McpServerConfig
  static sse(name: string, url: string): McpServerConfig
  static http(name: string, url: string): McpServerConfig
  withArg(arg: string): this
  withEnv(key: string, value: string): this
  withTimeout(secs: number): this
  withBearerToken(token: string): this
  withApiKey(header: string, key: string): this
  get name(): string
  get transport(): string
}
export declare class McpConfig {
  constructor()
  withServer(server: McpServerConfig): this
  serverNames(): Array<string>
  getServer(name: string): any | null
  serverCount(): number
}
export declare class Tracer {
  constructor(serviceName: string)
  startSpan(name: string, kind?: SpanKind | undefined | null): JsSpan
  drainSpans(): Array<any>
  spanCount(): number
}
export declare class JsSpan {
  setAttribute(key: string, value: string): void
  setOk(): void
  setError(message: string): void
  addEvent(name: string): void
  end(): void
}
export declare class MetricsCollector {
  constructor()
  increment(name: string, value: number): void
  recordDuration(name: string, ms: number): void
  gauge(name: string, value: number): void
  snapshot(): any
}
export declare class IntentRoute {
  constructor(agent: string)
  pattern(pattern: string): this
  priority(priority: number): this
  keyword(keyword: string): this
}
export declare class CommonIntents {
  static greeting(agent: string): CommonIntents
  static question(agent: string): CommonIntents
  static code(agent: string): CommonIntents
  static search(agent: string): CommonIntents
  static task(agent: string): CommonIntents
}
export declare class IntentRouter {
  constructor()
  route(intentRoute: IntentRoute): this
  defaultAgent(agent: string): this
  minConfidence(min: number): this
  classifyAndRoute(input: string): JsRoutingDecision | null
}
export declare class SessionStore {
  constructor()
  create(id: string): JsSession
  get(id: string): JsSession | null
  remove(id: string): boolean
  exists(id: string): boolean
  listIds(): Array<string>
  count(): number
  clear(): void
}
export declare class PipelineContext {
  constructor()
  set(key: string, value: any): void
  get(key: string): any | null
  getString(key: string): string | null
  setMetadata(key: string, value: any): void
}
export declare class PromptTemplate {
  constructor(template: string)
  render(vars: Record<string, string>): string
  variables(): Array<string>
}
export declare class PromptLibrary {
  constructor()
  add(name: string, template: string): void
  addWithCategory(name: string, template: string, category: string): void
  render(name: string, vars: Record<string, string>): string
  has(name: string): boolean
  list(): Array<string>
  categories(): Array<string>
  listByCategory(category: string): Array<string>
  remove(name: string): boolean
  len(): number
  isEmpty(): boolean
}
export declare class JsPromptConfig {
  constructor(name: string, template: string)
  description(desc: string): this
  category(cat: string): this
  defaultVar(key: string, value: string): this
  tag(tag: string): this
}
export declare class CommonPrompts {
  static summarize(): CommonPrompts
  static translate(): CommonPrompts
  static qa(): CommonPrompts
  static codeReview(): CommonPrompts
  static classify(): CommonPrompts
  static extractEntities(): CommonPrompts
  static rewrite(): CommonPrompts
  static chainOfThought(): CommonPrompts
  static library(): CommonPrompts
}
export declare class VectorIndex {
  constructor()
  add(document: JsEmbeddedDocument): void
  addBatch(documents: Array<JsEmbeddedDocument>): void
  remove(id: string): boolean
  get(id: string): JsEmbeddedDocument | null
  search(queryEmbedding: Array<number>, topK: number): Array<JsVectorSearchResult>
  searchWithThreshold(queryEmbedding: Array<number>, topK: number, minScore: number): Array<JsVectorSearchResult>
  len(): number
  isEmpty(): boolean
  clear(): void
  ids(): Array<string>
}
export declare class RetryConfig {
  constructor(maxRetries: number)
  initialDelay(ms: number): this
  maxDelay(ms: number): this
  backoffMultiplier(multiplier: number): this
  get maxRetries(): number
  delayForAttempt(attempt: number): number
}
export declare class OnceSchedule {
  static now(): OnceSchedule
  static afterSecs(seconds: number): OnceSchedule
  shouldRun(): boolean
  isExhausted(): boolean
  advance(): void
}
export declare class IntervalSchedule {
  constructor(seconds: number)
  static fromSecs(seconds: number): IntervalSchedule
  static fromMins(minutes: number): IntervalSchedule
  shouldRun(): boolean
  advance(): void
  runCount(): number
}
export declare class CronSchedule {
  constructor(expression: string)
  static everyMinute(): CronSchedule
  static hourly(): CronSchedule
  static daily(): CronSchedule
  shouldRun(): boolean
  isValid(): boolean
  advance(): void
  get expression(): string
}
export declare class CompletionStream {
  next(): Promise<ChatCompletionChunk | null>
}
export declare class ToolRegistry {
  constructor()
  registerTool(name: string, description: string, parameters: any): void
  unregister(name: string): boolean
  contains(name: string): boolean
  len(): number
  isEmpty(): boolean
  names(): Array<string>
  definitions(): any
}
export declare class ToolExecutor {
  constructor(registry: ToolRegistry)
  hasTool(name: string): boolean
  execute(name: string, args: any): JsToolResultData
  executeWithId(toolCallId: string, name: string, args: any): JsToolResultData
}
